# Generated by Django 6.0.6 on 2026-07-09 21:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0006_populate_states_and_lgas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('escrowed', 'Funds Locked'), ('completed', 'Completed'), ('cancelled', 'Cancelled/Refunded'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('is_inspected', models.BooleanField(default=False)),
                ('is_documents_verified', models.BooleanField(default=False)),
                ('buyer_approved', models.BooleanField(default=False)),
                ('seller_approved', models.BooleanField(default=False)),
                ('terms', models.TextField(blank=True, default='', help_text='Proposed terms, duration, or specifications')),
                ('dispute_reason', models.TextField(blank=True, default='', help_text='Reason for raising a dispute')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_purchases', to=settings.AUTH_USER_MODEL)),
                ('property_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrows', to='properties.propertylisting')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'escrow_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
