# Generated by Django 6.0.6 on 2026-09-10 17:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowtransaction',
            name='buyer_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='buyer_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='in_mediation',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='mediation_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='mediation_reason',
            field=models.TextField(blank=True, default='', help_text='Reason mediation was triggered'),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='mediation_resolution_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='mediation_resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='mediation_status',
            field=models.CharField(choices=[('none', 'No Mediation'), ('opened', 'Mediation Case Opened'), ('under_review', 'Team Reviewing'), ('resolved', 'Mediation Resolved')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='seller_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='seller_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='escrowtransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('escrowed', 'Funds Locked'), ('in_mediation', 'In Mediation'), ('completed', 'Completed'), ('cancelled', 'Cancelled/Refunded'), ('disputed', 'Disputed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='EscrowMediation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('reason', models.TextField()),
                ('evidence_notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('opened', 'Opened'), ('in_review', 'Under Investigation'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='opened', max_length=20)),
                ('resolution', models.CharField(blank=True, choices=[('refund_buyer', 'Refund Buyer In Full'), ('release_seller', 'Disburse Funds to Seller'), ('split', 'Partial Split / Settlement'), ('mutual_agreement', 'Resolved by Mutual Agreement')], default='', max_length=30)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('assigned_team', models.CharField(default='LandMarket Trust & Compliance Team', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('escrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediations', to='escrows.escrowtransaction')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_mediations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'escrow_mediations',
                'ordering': ['-created_at'],
            },
        ),
    ]
