# Generated by Django 6.0.6 on 2026-06-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Required for full profile verification.', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_address',
            field=models.CharField(blank=True, default='', help_text='Full residential or business address.', max_length=500),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_kyc_verified',
            field=models.BooleanField(default=False, help_text='True when the user has passed KYC identity verification.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_profile_complete',
            field=models.BooleanField(default=False, help_text='True when the user has filled in all required profile fields.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Profile photo for identity.', null=True, upload_to='users/profile_photos/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('realtor', 'Realtor'), ('agent', 'Agent'), ('admin', 'Admin')], db_index=True, default='buyer', max_length=10),
        ),
    ]
