# Generated by Django 6.0.6 on 2026-06-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_date_of_birth_customuser_full_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('realtor', 'Realtor'), ('agent', 'Agent'), ('architect', 'Architect'), ('admin', 'Admin')], db_index=True, default='buyer', max_length=10),
        ),
    ]
