# Generated by Django 6.0.6 on 2026-07-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('realtor', 'Realtor'), ('agent', 'Agent'), ('architect', 'Architect'), ('landlord', 'Landlord'), ('developer', 'Developer'), ('admin', 'Admin')], db_index=True, default='buyer', max_length=10),
        ),
    ]
