# Generated by Django 6.0.6 on 2026-06-03 23:34

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=300)),
                ('description', models.TextField(help_text='Supports markdown formatting for rich property descriptions.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in Nigerian Naira (₦).', max_digits=14)),
                ('land_size', models.DecimalField(decimal_places=2, help_text='Size in square meters.', max_digits=10)),
                ('location', models.CharField(db_index=True, help_text='Human-readable location string (e.g., "Lekki Phase 1, Lagos").', max_length=300)),
                ('state', models.CharField(blank=True, db_index=True, default='', help_text='State (e.g., "Lagos", "Abuja").', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude for map placement.', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude for map placement.', max_digits=9, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold')], db_index=True, default='available', max_length=15)),
                ('view_count', models.PositiveIntegerField(default=0, editable=False)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='realtors.realtorprofile')),
            ],
            options={
                'verbose_name': 'Property Listing',
                'verbose_name_plural': 'Property Listings',
                'db_table': 'property_listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='Uploaded to Cloudinary CDN automatically.', upload_to='properties/images/')),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='The primary image is used as the listing thumbnail.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.propertylisting')),
            ],
            options={
                'verbose_name': 'Property Image',
                'verbose_name_plural': 'Property Images',
                'db_table': 'property_images',
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('property_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='properties.propertylisting')),
            ],
            options={
                'verbose_name': 'Property View',
                'verbose_name_plural': 'Property Views',
                'db_table': 'property_views',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='propertylisting',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='property_search_idx'),
        ),
        migrations.AddIndex(
            model_name='propertylisting',
            index=models.Index(fields=['price'], name='property_price_idx'),
        ),
        migrations.AddIndex(
            model_name='propertylisting',
            index=models.Index(fields=['land_size'], name='property_size_idx'),
        ),
        migrations.AddIndex(
            model_name='propertylisting',
            index=models.Index(fields=['-created_at', 'status'], name='property_date_status_idx'),
        ),
    ]
