# Generated by Django 6.0.6 on 2026-06-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='If true, property appears in the featured carousel.'),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='listing_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('upcoming', 'Upcoming Estate')], db_index=True, default='regular', max_length=15),
        ),
    ]
