# Generated by Django 6.0.6 on 2026-06-15 16:40


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_propertylisting_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='video',
            field=models.FileField(blank=True, help_text='Optional promotional video for the property.', null=True, upload_to='properties/videos/'),
        ),
    ]
