# Generated by Django 6.0.6 on 2026-07-08 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '__first__'),
        ('landlords', '__first__'),
        ('properties', '0003_propertylisting_video'),
        ('realtors', '0003_realtorreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='developers.developerprofile'),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='landlord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='landlords.landlordprofile'),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='realtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='realtors.realtorprofile'),
        ),
    ]
