# Generated by Django 6.0.6 on 2026-07-08 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_propertylisting_developer_propertylisting_landlord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'verbose_name': 'LGA',
                'verbose_name_plural': 'LGAs',
                'db_table': 'property_lgas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'db_table': 'property_states',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='agency_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='bathrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='bedrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='built_up_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Built-up area in square meters (for houses/apartments).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='caution_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='has_c_of_o',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='has_drainage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='has_electricity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='has_generator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='has_security',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='has_survey_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='has_water',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='legal_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='property_category',
            field=models.CharField(choices=[('land', 'Land'), ('building', 'Building')], db_index=True, default='land', max_length=20),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='property_type',
            field=models.CharField(choices=[('plot', 'Plot'), ('estate', 'Upcoming Estate'), ('house', 'House'), ('apartment', 'Apartment'), ('commercial', 'Commercial Space'), ('office', 'Office Space'), ('short_let_apartment', 'Short-Let Apartment')], db_index=True, default='plot', max_length=30),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='rent_frequency',
            field=models.CharField(blank=True, choices=[('yearly', 'Yearly'), ('monthly', 'Monthly'), ('daily', 'Daily')], db_index=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent'), ('lease', 'For Lease'), ('short_let', 'Short-Let'), ('regular', 'Regular'), ('upcoming', 'Upcoming Estate')], db_index=True, default='sale', max_length=15),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='lga_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.lga'),
        ),
        migrations.AddField(
            model_name='lga',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lgas', to='properties.state'),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='state_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.state'),
        ),
        migrations.AlterUniqueTogether(
            name='lga',
            unique_together={('name', 'state')},
        ),
    ]
