# Generated by Django 6.0.6 on 2026-07-09 22:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_populate_states_and_lgas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='is_title_verified',
            field=models.BooleanField(default=False, help_text='Indicates if the property title has been verified by the LandMarket legal team.'),
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('c_of_o', 'Certificate of Occupancy'), ('deed_of_assignment', 'Deed of Assignment'), ('survey_plan', 'Registered Survey Plan'), ('gazette', 'Excision Gazette'), ('other', 'Other Document')], default='other', max_length=30)),
                ('file', models.FileField(upload_to='property_documents/')),
                ('is_verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.propertylisting')),
            ],
            options={
                'verbose_name': 'Property Legal Document',
                'verbose_name_plural': 'Property Legal Documents',
                'db_table': 'property_documents',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Search'), ('in_progress', 'Search In Progress'), ('approved', 'Approved / Title Clear'), ('rejected', 'Rejected / Title Disputed')], default='pending', max_length=20)),
                ('report_notes', models.TextField(blank=True, default='')),
                ('fee_charged', models.DecimalField(decimal_places=2, default=10000.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='properties.propertylisting')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Title Verification Request',
                'verbose_name_plural': 'Title Verification Requests',
                'db_table': 'property_verification_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
