# Generated by Django 6.0.6 on 2026-07-09 22:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_propertylisting_is_title_verified_propertydocument_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('view', 'Page View'), ('whatsapp_click', 'WhatsApp Click'), ('phone_click', 'Phone Call Click'), ('escrow_propose', 'Escrow Inquiry')], db_index=True, default='view', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('property_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='properties.propertylisting')),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewed_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property Analytics Event',
                'verbose_name_plural': 'Property Analytics Events',
                'db_table': 'property_analytics_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
