# Generated by Django 6.0.6 on 2026-07-22 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architects', '0001_initial'),
        ('properties', '0009_savedsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='architect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='architects.architectprofile'),
        ),
    ]
