# Generated by Django 6.0.6 on 2026-09-10 17:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_add_architect_fk_to_property_listing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyanalyticsevent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='propertydocument',
            options={'ordering': ['uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='propertyview',
            options={'ordering': ['-viewed_at']},
        ),
        migrations.AlterModelOptions(
            name='savedsearch',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='verificationrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='is_under_review',
            field=models.BooleanField(db_index=True, default=False, help_text='Flagged automatically if multiple community fraud reports are filed.'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='properties/images/'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('under_review', 'Under Investigation / Flagged')], db_index=True, default='available', max_length=15),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='PropertyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('reason', models.CharField(choices=[('suspicious_payment', 'Demanded Direct / Offline Payment'), ('fake_agent', 'Fake Agent / Impersonation'), ('duplicate_listing', 'Duplicate / Stolen Photos'), ('disputed_land', 'Disputed Land / Omo Onile Conflict'), ('already_sold', 'Already Sold / Unavailable'), ('price_bait', 'Price Baiting / Misleading Price'), ('other', 'Other Fraud / Safety Concern')], default='other', max_length=30)),
                ('description', models.TextField(help_text='Evidence details submitted by reporter.')),
                ('status', models.CharField(choices=[('pending', 'Pending Audit'), ('under_review', 'Under Investigation'), ('resolved', 'Resolved / Action Taken'), ('dismissed', 'Dismissed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('property_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='properties.propertylisting')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property Fraud Report',
                'verbose_name_plural': 'Property Fraud Reports',
                'db_table': 'property_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
