# Generated by Django 6.0.6 on 2026-06-03 23:34

import django.db.models.deletion
import realtors.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('whatsapp_link', models.CharField(help_text='WhatsApp link (https://wa.me/2348012345678) or phone number.', max_length=100, validators=[realtors.models.validate_whatsapp_link])),
                ('bio', models.TextField(blank=True, default='')),
                ('is_verified', models.BooleanField(default=False, help_text='Verified realtors get a badge on their listings.')),
                ('profile_picture', models.ImageField(blank=True, help_text='Uploaded to Cloudinary CDN automatically.', null=True, upload_to='realtors/profile_pictures/')),
                ('total_views', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='realtor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Realtor Profile',
                'verbose_name_plural': 'Realtor Profiles',
                'db_table': 'realtor_profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
