# Generated by Django 6.0.6 on 2026-06-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtorprofile',
            name='company_location',
            field=models.CharField(blank=True, default='', help_text='Physical office/company location.', max_length=300),
        ),
    ]
