# Generated by Django 6.0.6 on 2026-06-05 23:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Pro, Premium, Pro Plus', max_length=50, unique=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, help_text='Monthly price in Naira', max_digits=10)),
                ('max_listings', models.PositiveIntegerField(help_text='Maximum allowed active listings')),
                ('boosts_per_month', models.PositiveIntegerField(default=0, help_text='Number of listing boosts per month')),
                ('features', models.JSONField(default=list, help_text='List of feature strings for display')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Ordering for display')),
            ],
            options={
                'db_table': 'subscription_plans',
                'ordering': ['order', 'price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('past_due', 'Past Due')], default='active', max_length=20)),
                ('current_period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_period_end', models.DateTimeField()),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('paystack_subscription_code', models.CharField(blank=True, default='', max_length=100)),
                ('paystack_email_token', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscribers', to='subscriptions.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_subscriptions',
            },
        ),
    ]
