# Generated by Django 6.0.6 on 2026-06-28 15:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchitectProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('specialization', models.CharField(blank=True, default='Residential & Commercial', help_text='e.g., Residential, Commercial, Interior Design, Urban Planning', max_length=100)),
                ('years_of_experience', models.PositiveIntegerField(default=1)),
                ('bio', models.TextField(blank=True, default='')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('whatsapp_link', models.URLField(blank=True, default='')),
                ('portfolio_url', models.URLField(blank=True, default='', help_text='Link to external design portfolio or website.', max_length=300)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='architects/profiles/')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='architect_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Architect Profile',
                'verbose_name_plural': 'Architect Profiles',
                'db_table': 'architect_profiles',
            },
        ),
        migrations.CreateModel(
            name='ArchitectReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rating from 1 to 5 stars')),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('architect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='architects.architectprofile')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='architect_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'architect_reviews',
                'ordering': ['-created_at'],
                'unique_together': {('architect', 'reviewer')},
            },
        ),
    ]
