# Generated by Django 6.0.6 on 2026-06-03 23:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaystackPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('listing_fee', 'Listing Fee'), ('featured_listing', 'Featured Listing'), ('verification_fee', 'Verification Fee')], default='listing_fee', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in Naira (₦).', max_digits=12)),
                ('reference', models.CharField(help_text='Paystack transaction reference.', max_length=100, unique=True)),
                ('paystack_access_code', models.CharField(blank=True, default='', max_length=100)),
                ('paystack_transaction_id', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'paystack_payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
