# Generated by Django 6.0.6 on 2026-06-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paystackpayment',
            name='payment_type',
            field=models.CharField(choices=[('listing_fee', 'Listing Fee'), ('featured_listing', 'Featured Listing'), ('verification_fee', 'Verification Fee'), ('agent_connection', 'Agent Connection Fee'), ('meeting_fee', 'Meeting Fee')], default='listing_fee', max_length=20),
        ),
    ]
