# Generated by Django 6.0.6 on 2026-06-05 22:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0002_alter_paystackpayment_payment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('company_location', models.CharField(blank=True, default='', max_length=300)),
                ('bio', models.TextField(blank=True, default='')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('whatsapp_link', models.URLField(blank=True, default='')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='agents/profiles/')),
                ('is_verified', models.BooleanField(default=False)),
                ('total_connections', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Profile',
                'verbose_name_plural': 'Agent Profiles',
                'db_table': 'agent_profiles',
            },
        ),
        migrations.CreateModel(
            name='AgentLocationPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=100)),
                ('location', models.CharField(help_text='City or specific area.', max_length=200)),
                ('connection_fee', models.DecimalField(decimal_places=2, help_text='Fee in Naira (₦) required to unlock contact and chat.', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_prices', to='agents.agentprofile')),
            ],
            options={
                'db_table': 'agent_location_pricing',
                'unique_together': {('agent', 'state', 'location')},
            },
        ),
        migrations.CreateModel(
            name='AgentConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('active', 'Active'), ('completed', 'Completed')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for the connection.', null=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paystackpayment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_connections', to=settings.AUTH_USER_MODEL)),
                ('location_pricing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agentlocationpricing')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_connections', to='agents.agentprofile')),
            ],
            options={
                'db_table': 'agent_connections',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'agent')},
            },
        ),
    ]
