# Generated by Django 6.0.6 on 2026-06-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agentreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconnection',
            name='agent_completed',
            field=models.BooleanField(default=False, help_text='Agent accepted that the transaction is completed.'),
        ),
        migrations.AddField(
            model_name='agentconnection',
            name='buyer_completed',
            field=models.BooleanField(default=False, help_text='Buyer accepted that the transaction is completed.'),
        ),
        migrations.AlterField(
            model_name='agentconnection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('active', 'Active'), ('closed', 'Closed (Escrow Released)')], default='pending', max_length=15),
        ),
    ]
