# Generated by Django 6.0.6 on 2026-07-08 22:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('company_location', models.CharField(blank=True, default='', help_text='Physical office/company address.', max_length=300)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('whatsapp_link', models.CharField(blank=True, default='', help_text='WhatsApp link (https://wa.me/2348012345678) or phone number.', max_length=100)),
                ('bio', models.TextField(blank=True, default='')),
                ('portfolio_url', models.URLField(blank=True, default='', help_text='Link to external website or portfolio.', max_length=300)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='developers/profiles/')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='developer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Developer Profile',
                'verbose_name_plural': 'Developer Profiles',
                'db_table': 'developer_profiles',
            },
        ),
        migrations.CreateModel(
            name='DeveloperReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rating from 1 to 5 stars')),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='developers.developerprofile')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'developer_reviews',
                'ordering': ['-created_at'],
                'unique_together': {('developer', 'reviewer')},
            },
        ),
    ]
