# Generated by Django 6.0.6 on 2026-09-12 11:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0011_alter_propertyanalyticsevent_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('advance_fee_fraud', 'Advance Fee / Demanded Direct Offline Payment'), ('fake_agent', 'Fake Agent / Impersonation'), ('forged_documents', 'Fake or Forged Title Documents'), ('land_grabbing_extortion', 'Land Grabbers (Omo Onile) / Extortion & Threats'), ('duplicate_fake_listing', 'Duplicate / Stolen Photos / Fake Listing'), ('breach_of_escrow', 'Breach of Escrow / Contract Default'), ('cybercrime_phishing', 'Cybercrime / Account Takeover / Phishing'), ('inspection_safety_incident', 'Physical Danger / Inspection Safety Incident'), ('other_crime', 'Other Crime or Platform Offense')], db_index=True, default='other_crime', max_length=40)),
                ('title', models.CharField(help_text='Brief summary headline of the crime or offense.', max_length=255)),
                ('description', models.TextField(help_text='Detailed chronological narrative of the crime or offense.')),
                ('suspect_name', models.CharField(blank=True, default='', help_text='Suspect individual or company name.', max_length=200)),
                ('suspect_phone', models.CharField(blank=True, default='', help_text='Phone or WhatsApp number used by suspect.', max_length=50)),
                ('suspect_bank_account', models.CharField(blank=True, default='', help_text='Bank name and account number if money was requested.', max_length=200)),
                ('financial_loss', models.DecimalField(decimal_places=2, default=0.0, help_text='Estimated financial loss incurred in Naira (₦).', max_digits=12)),
                ('incident_date', models.DateField(blank=True, help_text='Date the offense occurred.', null=True)),
                ('incident_location', models.CharField(blank=True, default='', help_text='City, LGA, state, or address where offense took place.', max_length=255)),
                ('evidence_file', models.FileField(blank=True, help_text='Screenshot, chat export, payment receipt, or forged document.', null=True, upload_to='crime_reports/evidence/')),
                ('evidence_file_2', models.FileField(blank=True, help_text='Secondary supporting evidence file.', null=True, upload_to='crime_reports/evidence/')),
                ('status', models.CharField(choices=[('pending', 'Pending Compliance Audit'), ('under_investigation', 'Under Active Investigation'), ('escalated_to_authorities', 'Escalated to Law Enforcement (Police / EFCC)'), ('action_taken', 'Action Taken (Account/Listing Suspended)'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed / Inconclusive')], db_index=True, default='pending', max_length=30)),
                ('police_report_reference', models.CharField(blank=True, default='', help_text='Police SCID or EFCC petition reference tracking ID.', max_length=100)),
                ('admin_notes', models.TextField(blank=True, default='', help_text='Internal notes made by Trust & Safety compliance officers.')),
                ('resolution_summary', models.TextField(blank=True, default='', help_text='Public or reporter-facing resolution explanation.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('property_listing', models.ForeignKey(blank=True, help_text='Property listing involved if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crime_reports', to='properties.propertylisting')),
                ('reported_user', models.ForeignKey(blank=True, help_text='User or agent account reported if on platform.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(help_text='Authenticated user filing the crime report.', on_delete=django.db.models.deletion.CASCADE, related_name='crime_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crime & Offense Report',
                'verbose_name_plural': 'Crime & Offense Reports',
                'db_table': 'crime_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
