# Generated by Django 6.0.6 on 2026-06-05 22:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='dojah', max_length=50)),
                ('verification_type', models.CharField(choices=[('bvn', 'Bank Verification Number'), ('nin', 'National Identification Number'), ('drivers_license', "Driver's License")], max_length=20)),
                ('id_number', models.CharField(help_text='The BVN, NIN, or license number submitted for verification.', max_length=50)),
                ('reference_id', models.CharField(blank=True, default='', help_text='Dojah transaction reference.', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='pending', max_length=15)),
                ('response_data', models.JSONField(blank=True, default=dict, help_text='Full response from the KYC provider.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Verification',
                'verbose_name_plural': 'KYC Verifications',
                'db_table': 'kyc_verifications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
