# Generated by Django 6.0.6 on 2026-09-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycverification',
            name='document_image',
            field=models.FileField(blank=True, help_text='Uploaded photo of the ID card or CAC certificate.', null=True, upload_to='kyc_documents/'),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='document_number',
            field=models.CharField(blank=True, default='', help_text='ID card number or CAC Registration / BN number.', max_length=100),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for rejection if verification failed.'),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='id_number',
            field=models.CharField(blank=True, default='', help_text='Legacy ID reference if applicable.', max_length=100),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='provider',
            field=models.CharField(default='document_upload', max_length=50),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='reference_id',
            field=models.CharField(blank=True, default='', help_text='Internal or third-party verification reference.', max_length=100),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='response_data',
            field=models.JSONField(blank=True, default=dict, help_text='Metadata or review notes.'),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('failed', 'Rejected'), ('expired', 'Expired')], db_index=True, default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='verification_type',
            field=models.CharField(choices=[('drivers_license', "Driver's License"), ('international_passport', 'International Passport'), ('voters_card', "Voter's Card"), ('cac_certificate', 'CAC Registration Certificate'), ('national_id', 'National ID Card/Slip')], default='drivers_license', max_length=30),
        ),
    ]
